title:               Jak Lewis
include:             ['_pages']
# You may need to change the base URL depending on your deploy configuration.
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false


permalink:           pretty

plugins:
  - jekyll-relative-links

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  pages:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_pages/**/*.md"
    values:
      layout: "page"
